<a href="https://colab.research.google.com/github/santiagorodmon/TelecomX_LATAM/blob/main/01_extraccion_datos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 📌 Extracción

In [112]:
!git clone https://github.com/santiagorodmon/TelecomX_LATAM.git
%cd TelecomX_LATAM

Cloning into 'TelecomX_LATAM'...
remote: Enumerating objects: 13, done.
remote: Counting objects: 100% (13/13), done.
remote: Compressing objects: 100% (9/9), done.
Receiving objects: 100% (13/13), done.
remote: Total 13 (delta 0), reused 0 (delta 0), pack-reused 0 (from 0)
/content/TelecomX_LATAM/TelecomX_LATAM/TelecomX_LATAM


In [113]:
import pandas as pd

In [114]:
datos = pd.read_json('https://raw.githubusercontent.com/ingridcristh/challenge2-data-science-LATAM/refs/heads/main/TelecomX_Data.json')
datos.head()

,customerID,Churn,customer,phone,internet,account
0,0002-ORFBO,No,"{'gender': 'Female', 'SeniorCitizen': 0, 'Part...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'DSL', 'OnlineSecurity': '...","{'Contract': 'One year', 'PaperlessBilling': '..."
1,0003-MKNFE,No,"{'gender': 'Male', 'SeniorCitizen': 0, 'Partne...","{'PhoneService': 'Yes', 'MultipleLines': 'Yes'}","{'InternetService': 'DSL', 'OnlineSecurity': '...","{'Contract': 'Month-to-month', 'PaperlessBilli..."
2,0004-TLHLJ,Yes,"{'gender': 'Male', 'SeniorCitizen': 0, 'Partne...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'Fiber optic', 'OnlineSecu...","{'Contract': 'Month-to-month', 'PaperlessBilli..."
3,0011-IGKFF,Yes,"{'gender': 'Male', 'SeniorCitizen': 1, 'Partne...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'Fiber optic', 'OnlineSecu...","{'Contract': 'Month-to-month', 'PaperlessBilli..."
4,0013-EXCHZ,Yes,"{'gender': 'Female', 'SeniorCitizen': 1, 'Part...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'Fiber optic', 'OnlineSecu...","{'Contract': 'Month-to-month', 'PaperlessBilli..."


In [115]:
datos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7267 entries, 0 to 7266
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   customerID  7267 non-null   object
 1   Churn       7267 non-null   object
 2   customer    7267 non-null   object
 3   phone       7267 non-null   object
 4   internet    7267 non-null   object
 5   account     7267 non-null   object
dtypes: object(6)
memory usage: 340.8+ KB


In [116]:
datos.shape

(7267, 6)

## Desanidar columnas de diccionarios y sobreescribir df

In [117]:
columnas_anidadas = ['customer', 'phone', 'internet', 'account']

datos = pd.concat([datos.drop(columns=columnas_anidadas)] +
                     [pd.json_normalize(datos[col]) for col in columnas_anidadas], axis=1)

datos.head()

,customerID,Churn,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,...,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,Charges.Monthly,Charges.Total
0,0002-ORFBO,No,Female,0,Yes,Yes,9,Yes,No,DSL,...,Yes,No,Yes,Yes,No,One year,Yes,Mailed check,65.6,593.3
1,0003-MKNFE,No,Male,0,No,No,9,Yes,Yes,DSL,...,No,No,No,No,Yes,Month-to-month,No,Mailed check,59.9,542.4
2,0004-TLHLJ,Yes,Male,0,No,No,4,Yes,No,Fiber optic,...,No,Yes,No,No,No,Month-to-month,Yes,Electronic check,73.9,280.85
3,0011-IGKFF,Yes,Male,1,Yes,No,13,Yes,No,Fiber optic,...,Yes,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,98.0,1237.85
4,0013-EXCHZ,Yes,Female,1,Yes,No,3,Yes,No,Fiber optic,...,No,No,Yes,Yes,No,Month-to-month,Yes,Mailed check,83.9,267.4


In [118]:
datos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7267 entries, 0 to 7266
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   customerID        7267 non-null   object 
 1   Churn             7267 non-null   object 
 2   gender            7267 non-null   object 
 3   SeniorCitizen     7267 non-null   int64  
 4   Partner           7267 non-null   object 
 5   Dependents        7267 non-null   object 
 6   tenure            7267 non-null   int64  
 7   PhoneService      7267 non-null   object 
 8   MultipleLines     7267 non-null   object 
 9   InternetService   7267 non-null   object 
 10  OnlineSecurity    7267 non-null   object 
 11  OnlineBackup      7267 non-null   object 
 12  DeviceProtection  7267 non-null   object 
 13  TechSupport       7267 non-null   object 
 14  StreamingTV       7267 non-null   object 
 15  StreamingMovies   7267 non-null   object 
 16  Contract          7267 non-null   object 


##1. Valores nulos

In [119]:
print('Datos null = ',datos.isnull().sum())
print('Datos NA = ',datos.isna().sum())

Datos null =  customerID          0
Churn               0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
Charges.Monthly     0
Charges.Total       0
dtype: int64
Datos NA =  customerID          0
Churn               0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
Charges.Monthly     0
Charges.Total       0
dtype: int64


##2. Duplicados

In [120]:
print("Filas duplicadas:", datos.duplicated().sum())
print("customerID duplicados:", datos['customerID'].duplicated().sum())

Filas duplicadas: 0
customerID duplicados: 0


In [121]:
datos.dtypes

,0
customerID,object
Churn,object
gender,object
SeniorCitizen,int64
Partner,object
Dependents,object
tenure,int64
PhoneService,object
MultipleLines,object
InternetService,object


In [122]:
datos['SeniorCitizen'].unique()[:10]

array([0, 1])

In [123]:
datos['tenure'].unique()[:10]

array([ 9,  4, 13,  3, 71, 63,  7, 65, 54, 72])

In [124]:
datos['Charges.Monthly'].unique()[:10]

array([ 65.6 ,  59.9 ,  73.9 ,  98.  ,  83.9 ,  69.4 , 109.7 ,  84.65,
        48.2 ,  90.45])

In [125]:
datos['Charges.Total'].unique()[:10]

array(['593.3', '542.4', '280.85', '1237.85', '267.4', '571.45',
       '7904.25', '5377.8', '340.35', '5957.9'], dtype=object)

In [126]:
datos['Charges.Total'] = pd.to_numeric(datos['Charges.Total'], errors='coerce')
datos['Charges.Total'].unique()[:10]

array([ 593.3 ,  542.4 ,  280.85, 1237.85,  267.4 ,  571.45, 7904.25,
       5377.8 ,  340.35, 5957.9 ])

In [127]:
categoricas = ['Churn', 'gender', 'Partner', 'Dependents', 'PhoneService', 'MultipleLines',
               'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection',
               'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract',
               'PaperlessBilling', 'PaymentMethod']

for col in categoricas:
    print(f"\n{col}:")
    print(datos[col].value_counts(dropna=False))


Churn:
Churn
No     5174
Yes    1869
        224
Name: count, dtype: int64

gender:
gender
Male      3675
Female    3592
Name: count, dtype: int64

Partner:
Partner
No     3749
Yes    3518
Name: count, dtype: int64

Dependents:
Dependents
No     5086
Yes    2181
Name: count, dtype: int64

PhoneService:
PhoneService
Yes    6560
No      707
Name: count, dtype: int64

MultipleLines:
MultipleLines
No                  3495
Yes                 3065
No phone service     707
Name: count, dtype: int64

InternetService:
InternetService
Fiber optic    3198
DSL            2488
No             1581
Name: count, dtype: int64

OnlineSecurity:
OnlineSecurity
No                     3608
Yes                    2078
No internet service    1581
Name: count, dtype: int64

OnlineBackup:
OnlineBackup
No                     3182
Yes                    2504
No internet service    1581
Name: count, dtype: int64

DeviceProtection:
DeviceProtection
No                     3195
Yes                    2491
No intern

In [128]:
datos['Cuentas_Diarias'] = datos['Charges.Monthly'] / 30
datos['Cuentas_Diarias'].head()

,Cuentas_Diarias
0,2.186667
1,1.996667
2,2.463333
3,3.266667
4,2.796667


## Estandarización y transformación de datos

In [129]:
traduccion_columnas = {
    'customerID': 'ID_Cliente',
    'Churn': 'Evasion',
    'gender': 'Genero',
    'SeniorCitizen': 'Adulto_Mayor',
    'Partner': 'Pareja',
    'Dependents': 'Dependientes',
    'tenure': 'Antiguedad',
    'PhoneService': 'Servicio_Telefonico',
    'MultipleLines': 'Multiples_Lineas',
    'InternetService': 'Servicio_Internet',
    'OnlineSecurity': 'Seguridad_Online',
    'OnlineBackup': 'Backup_Online',
    'DeviceProtection': 'Proteccion_Dispositivo',
    'TechSupport': 'Soporte_Tecnico',
    'StreamingTV': 'Streaming_TV',
    'StreamingMovies': 'Streaming_Peliculas',
    'Contract': 'Contrato',
    'PaperlessBilling': 'Factura_Electronica',
    'PaymentMethod': 'Metodo_Pago',
    'Charges.Monthly': 'Cargo_Mensual',
    'Charges.Total': 'Cargo_Total',
    'Cuentas_Diarias': 'Valor_Diario'
}

datos.rename(columns=traduccion_columnas, inplace=True)
datos.columns.tolist()

['ID_Cliente',
 'Evasion',
 'Genero',
 'Adulto_Mayor',
 'Pareja',
 'Dependientes',
 'Antiguedad',
 'Servicio_Telefonico',
 'Multiples_Lineas',
 'Servicio_Internet',
 'Seguridad_Online',
 'Backup_Online',
 'Proteccion_Dispositivo',
 'Soporte_Tecnico',
 'Streaming_TV',
 'Streaming_Peliculas',
 'Contrato',
 'Factura_Electronica',
 'Metodo_Pago',
 'Cargo_Mensual',
 'Cargo_Total',
 'Valor_Diario']

In [130]:
datos.head()

,ID_Cliente,Evasion,Genero,Adulto_Mayor,Pareja,Dependientes,Antiguedad,Servicio_Telefonico,Multiples_Lineas,Servicio_Internet,...,Proteccion_Dispositivo,Soporte_Tecnico,Streaming_TV,Streaming_Peliculas,Contrato,Factura_Electronica,Metodo_Pago,Cargo_Mensual,Cargo_Total,Valor_Diario
0,0002-ORFBO,No,Female,0,Yes,Yes,9,Yes,No,DSL,...,No,Yes,Yes,No,One year,Yes,Mailed check,65.6,593.30,2.186667
1,0003-MKNFE,No,Male,0,No,No,9,Yes,Yes,DSL,...,No,No,No,Yes,Month-to-month,No,Mailed check,59.9,542.40,1.996667
2,0004-TLHLJ,Yes,Male,0,No,No,4,Yes,No,Fiber optic,...,Yes,No,No,No,Month-to-month,Yes,Electronic check,73.9,280.85,2.463333
3,0011-IGKFF,Yes,Male,1,Yes,No,13,Yes,No,Fiber optic,...,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,98.0,1237.85,3.266667
4,0013-EXCHZ,Yes,Female,1,Yes,No,3,Yes,No,Fiber optic,...,No,Yes,Yes,No,Month-to-month,Yes,Mailed check,83.9,267.40,2.796667


In [99]:
columnas_binarias = ['Evasion', 'Pareja', 'Dependientes', 'Servicio_Telefonico',
                     'Factura_Electronica', 'Adulto_Mayor','Seguridad_Online', 'Backup_Online', 'Proteccion_Dispositivo',
                      'Soporte_Tecnico', 'Streaming_TV', 'Streaming_Peliculas', 'Multiples_Lineas']

columnas_servicios = ['Seguridad_Online', 'Backup_Online', 'Proteccion_Dispositivo',
                      'Soporte_Tecnico', 'Streaming_TV', 'Streaming_Peliculas', 'Multiples_Lineas']

for col in columnas_binarias:
    if col in datos.columns:
        if datos[col].dtype == 'object':
            datos[col] = datos[col].map({'Yes': 1, 'No': 0})
            print(f"{col} convertida a binaria (1=Yes, 0=No)")

Seguridad_Online convertida a binaria (1=Yes, 0=No)
Backup_Online convertida a binaria (1=Yes, 0=No)
Proteccion_Dispositivo convertida a binaria (1=Yes, 0=No)
Soporte_Tecnico convertida a binaria (1=Yes, 0=No)
Streaming_TV convertida a binaria (1=Yes, 0=No)
Streaming_Peliculas convertida a binaria (1=Yes, 0=No)
Multiples_Lineas convertida a binaria (1=Yes, 0=No)


In [131]:
for col in columnas_servicios:
    if col in datos.columns:
        nulos = datos[col].isnull().sum()
        if nulos > 0:
            print(f"{col}: {nulos} valores NaN (clientes sin servicio de internet)")
            datos[col] = datos[col].fillna(2)

In [133]:
datos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7267 entries, 0 to 7266
Data columns (total 22 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   ID_Cliente              7267 non-null   object 
 1   Evasion                 7267 non-null   object 
 2   Genero                  7267 non-null   object 
 3   Adulto_Mayor            7267 non-null   int64  
 4   Pareja                  7267 non-null   object 
 5   Dependientes            7267 non-null   object 
 6   Antiguedad              7267 non-null   int64  
 7   Servicio_Telefonico     7267 non-null   object 
 8   Multiples_Lineas        7267 non-null   object 
 9   Servicio_Internet       7267 non-null   object 
 10  Seguridad_Online        7267 non-null   object 
 11  Backup_Online           7267 non-null   object 
 12  Proteccion_Dispositivo  7267 non-null   object 
 13  Soporte_Tecnico         7267 non-null   object 
 14  Streaming_TV            7267 non-null   

In [138]:
datos['Cargo_Total'].isnull().sum()

np.int64(11)

In [141]:
nulos_cargo = datos[datos['Cargo_Total'].isnull()]
nulos_cargo['Antiguedad']

,Antiguedad
975,0
1775,0
1955,0
2075,0
2232,0
2308,0
2930,0
3134,0
3203,0
4169,0
